blueprint:
  name: Rolladen Sonnenschutz
  description: fährt Rolladen bei überschreiten von Grenzwerten nach unten um die Einstrahlung zu minimieren
  domain: automation
  input:
    target_cover:
      name: Rolladen
      description: Rolladen welcher gesteuert wird.
      selector:
        target:
          entity:
            domain: cover

trigger:
  - platform: numeric_state
    entity_id: sensor.weewx_temperatur_aussen
    for:
      hours: 0
      minutes: 5
      seconds: 0
    above: '25'

condition:
  - condition: numeric_state
    entity_id: sensor.dwd_speyer_forcast_today_temperature
    above: '29.9'

action:
  - if:
      - condition: numeric_state
        entity_id: sensor.dwd_speyer_forcast_today_temperature
        above: '33.9'
    then:
      - entity_id: !input target_cover
        type: set_position
        position: 20
  - entity_id: !input target_cover
    type: set_position
    position: 40